description: 'Markdown translation into any other language powered by ChatGPT'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  apikey:
    description: 'API Key'
    required: true
  provider:
    description: 'AI Provider'
    required: false
    default: 'openai'
  model:
    description: 'The language model to use.'
    required: false
    default: 'gpt-4o'
  prompt:
    description: 'The input prompt to generate the text from'
    required: false
    default: 'Please translate the given text into naturalistic {targetLanguage}.'
  systemPrompt:
    description: 'The system prompt to use that specifies the behavior of the model'
    required: false
  basePath:
    description: 'Replace the base path of openai api'
    required: false
  inputFiles:
    description: 'Input files to translate'
    required: false
  outputFiles:
    description: 'Output files to save'
    required: false
  languages:
    description: 'Language to translate to'
    required: false
  top_p:
    description: 'Controls diversity via nucleus sampling (0 to 1)'
    required: false
    default: '0.5'
  temperature:
    description: 'Controls randomness of the output (0 to 2)'
    required: false
    default: '0.3'
  max_tokens:
    description: 'Maximum number of tokens in the chat completion'
    required: false
  presence_penalty:
    description: 'Penalizes new tokens based on their existing presence (-2 to 2)'
    required: false
    default: '0'
  frequency_penalty:
    description: 'Penalizes new tokens based on their frequency (-2 to 2)'
    required: false
    default: '0'
  seed:
    description: 'Seed value for deterministic sampling'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'globe'
  color: 'green'
